approvedGitRepositories:
  - "**"

cacheFolder: ./.yarn/cache

enableGlobalCache: false

enableScripts: true

enableStrictSsl: false

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmScopes:
  kx2024:
    npmRegistryServer: "https://gitlab.com/api/v4/packages/npm/"

yarnPath: .yarn/releases/yarn-4.18.0.cjs
